# =====  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
# ============================================================================
---
- name: Check if IBM HTTP Administration Server nodeagent started
  ansible.builtin.systemd_service:
    name: ibm-ihs-admin.service
    state: started
  register: ihs_admin_status

- name: IBM HTTP Administration status
  ansible.builtin.fail:
    msg: |
      Service ibm-ihs-admin.service is not running.
      Output of `systemctl status ibm-ihs-admin.service`:
      {{ ihs_admin_status.stdout }}
      {{ ihs_admin_status.stderr }}
  when: ihs_admin_status | failed

- name: Check if IBM HTTP Server target started
  ansible.builtin.systemd_service:
    name: ibm-ihs-services.target
    state: started
  register: ihs_services_status

- name: IBM HTTP Server target status
  ansible.builtin.fail:
    msg: |
      Service target ibm-ihs-services.target is not running.
      Output of `ibm-ihs-services.target`:
      {{ ihs_services_status.stdout }}
      {{ ihs_services_status.stderr }}
  when: ihs_services_status | failed
