#======  ANSIBLE  ============================================================
#          NAME:  tasks/systemd.yml
#   DESCRIPTION:  Primary entry point for this play
#==============================================================================
---
- name: Check if IBM HTTP Administration  Server is started
  command: systemctl status ibm-ihs-admin.service
  ignore_errors: yes
  changed_when: false
  register: service_ihsadm_status

- name: IBM HTTP Administration Server status
  fail:
    msg: |
      Service ibm-ihs-admin.service is not running.
      Output of `systemctl status inm-ihs-admin.service`:
      {{ service_ihsadm_status.stdout }}
      {{ service_nodeagent_status.stderr }}
  when: service_ihsadm_status | failed

- name: Check if IBM HTTP Server services target started
  command: systemctl status ibm-ihs-services.target
  ignore_errors: yes
  changed_when: false
  register: service_ihsservices_status

- name: IBM HTTP Server services target status
  fail:
    msg: |
      Service target ibm-was-services.target is not running.
      Output of `ibm-ihs-services.target`:
      {{ service_ihsservives_status.stdout }}
      {{ service_wasprofile_status.stderr }}
  when: service_ihservices_status | failed
