#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  A06-websphere
#         USAGE:  . A06-websphere
#   DESCRIPTION:  Aliases for WebSphere Server Management
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

[[ -d /usr1/IBM/WebSphere/AppServer ]] || return;

if [[ -d /usr1/IBM/WebSphere/profiles/dmgr01 ]]; then
    alias startManager='/usr1/IBM/WebSphere/profiles/dmgr01/bin/startManager.sh';
    alias stopManager='/usr1/IBM/WebSphere/profiles/dmgr01/bin/stopManager.sh';

    alias wsadmin='/usr1/IBM/WebSphere/profiles/dmgr01/bin/wsadmin.sh -lang jython';
    alias runCCT='/usr1/IBM/WebSphere/profiles/dmgr01/bin/wsadmin.sh -conntype NONE -f /nas/pportal_software/IBM/WAS/CCT/ConfigDump.py';
fi

if [[ -d /usr1/IBM/WebSphere/profiles/PPSearch ]]; then
    alias startServer='/usr1/IBM/WebSphere/profiles/PPSearch/bin/startServer.sh';
    alias stopServer='/usr1/IBM/WebSphere/profiles/PPSearch/bin/stopServer.sh';

    alias startNode='/usr1/IBM/WebSphere/profiles/PPSearch/bin/startNode.sh';
    alias stopNode='/usr1/IBM/WebSphere/profiles/PPSearch/bin/stopNode.sh';

    alias wsadmin='/usr1/IBM/WebSphere/profiles/PPSearch/bin/wsadmin.sh -lang jython';
    alias runCCT='/usr1/IBM/WebSphere/profiles/PPSearch/bin/wsadmin.sh -conntype NONE -f ~/lib/wasadmin/cct/ConfigDump.py';
fi

if [[ -d /usr1/IBM/WebSphere/profiles/PPServices01 ]]; then
    alias startServer='/usr1/IBM/WebSphere/profiles/PPServices01/bin/startServer.sh';
    alias stopServer='/usr1/IBM/WebSphere/profiles/PPServices01/bin/stopServer.sh';

    alias startNode='/usr1/IBM/WebSphere/profiles/PPServices01/bin/startNode.sh';
    alias stopNode='/usr1/IBM/WebSphere/profiles/PPServices01/bin/stopNode.sh';

    alias wsadmin='/usr1/IBM/WebSphere/profiles/PPServices01/bin/wsadmin.sh -lang jython';
    alias runCCT='/usr1/IBM/WebSphere/profiles/PPServices01/bin/wsadmin.sh -conntype NONE -f ~/lib/wasadmin/cct/ConfigDump.py';
fi

if [[ -d /usr1/IBM/WebSphere/profiles/PPServices02 ]]; then
    alias startServer='/usr1/IBM/WebSphere/profiles/PPServices02/bin/startServer.sh';
    alias stopServer='/usr1/IBM/WebSphere/profiles/PPServices02/bin/stopServer.sh';

    alias startNode='/usr1/IBM/WebSphere/profiles/PPServices02/bin/startNode.sh';
    alias stopNode='/usr1/IBM/WebSphere/profiles/PPServices02/bin/stopNode.sh';

    alias wsadmin='/usr1/IBM/WebSphere/profiles/PPServices02/bin/wsadmin.sh -lang jython';
    alias runCCT='/usr1/IBM/WebSphere/profiles/PPServices02/bin/wsadmin.sh -conntype NONE -f ~/lib/wasadmin/cct/ConfigDump.py';
fi
