#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  A08-iim
#         USAGE:  . A08-iim
#   DESCRIPTION:  Customizations
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ ! -n "${IIM_INSTALL_ROOT}" ]] && [[ -d "${IIM_INSTALL_ROOT}" ]]; then
    alias imcl='${IIM_INSTALL_ROOT}/eclipse/tools/imcl';
fi
