#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  A08-iim
#         USAGE:  . A08-iim
#   DESCRIPTION:  Customizations
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

[[  /usr1/IBM/IIM ]] || return;

alias imcl='/usr1/IBM/IIM/eclipse/tools/imcl';
