# =====  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
# ============================================================================
---
- name: Send a notification email
  community.general.mail:
    body: "{{ message_body }}"
    host: smtp.gmail.com
    port: 587
    username: "{{ smtp_username }}"
    password: "{{ smtp_password }}"
    sender: "{{ smtp_username }}"
    subject: "{{ message_subject }}"
    to: "{{ message_to }}"
  delegate_to: localhost
  listen: send-notification
