#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  A07-ihs
#         USAGE:  . A07-ihs
#   DESCRIPTION:  Customizations
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ ! -n "${USER_INSTALL_ROOT}" ]] && [[ -d "${USER_INSTALL_ROOT}" ]]; then
    alias startIHS='${USER_INSTALL_ROOT}/bin/apachectl -k start';
    alias stopIHS='${USER_INSTALL_ROOT}/bin/apachectl -k stop';
fi
