#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  defaults
#         USAGE:  . defaults
#   DESCRIPTION:  Sets default commandline options and variables for various programs
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

[[ -z "${LOGNAME}" ]] && LOGNAME="$(whoami)"; declare -x LOGNAME;

declare -x LANG="en_US.UTF-8";
declare -x LC_ALL="en_US.UTF-8";
declare -x TIMEFORMAT=$'\nreal %3R\tuser %3U\tsys %3S\tpcpu %P\n';
declare -x LESS="-QR";
declare -ix IGNOREEOF=1;
declare -x BLOCKSIZE="K";
declare -x PAGER="less";
declare -x EDITOR="vim";
declare -x FCEDIT="vim";
declare -x VISUAL="vim";
declare -x DISPLAY=":0.0";
declare -x _TRUE="true";
declare -x _FALSE="false";
declare -ix THREAD_TIMEOUT=10;
declare -x MODIFIED_IFS="^";
declare -x RANDOM_GENERATOR="/dev/urandom";
declare -x ENTROPY_FILE="${HOME}/etc/entropy";
declare -ix ENTROPY_FILE_SIZE=16384;
declare -x SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket";

case "$(uname -s)" in
    [Cc][Yy][Gg]][Ww][Ii][Nn]*)
        declare -x TERM="ansi";
        declare -x PATHSEP=";";
        ;;
    [Ll][Ii]][Nn][Uu][Xx])
        declare -x TERM="linux";
        declare -x PATHSEP=":";
        ;;
    [Aa][Ii][Xx]|[Ss][Uu][Nn][Oo][Ss]|[Ss][Oo]][Ll][Aa][Rr][Ii][Ss])
        declare -x TERM="ansi";
        declare -x PATHSEP=":";
        ;;
esac
