#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  defaults
#         USAGE:  . defaults
#   DESCRIPTION:  Sets default commandline options and variables for various programs
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

[[ -z "${LOGNAME}" ]] && LOGNAME="$(whoami)";

LANG="en_US.UTF-8";
LC_ALL="en_US.UTF-8";
TIMEFORMAT=$'\nreal %3R\tuser %3U\tsys %3S\tpcpu %P\n';
LESS="-QR";
IGNOREEOF=1;
BLOCKSIZE="K";
PAGER="less";
EDITOR="vim";
FCEDIT="vim";
VISUAL="vim";
DISPLAY=":0.0";
_TRUE="true";
_FALSE="false";
THREAD_TIMEOUT=10;
MODIFIED_IFS="^";
RANDOM_GENERATOR="/dev/urandom";
ENTROPY_FILE="${HOME}/etc/entropy";
ENTROPY_FILE_SIZE=16384;
SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket";

case "$(uname -s)" in
    [Cc][Yy][Gg]][Ww][Ii][Nn]*)
        TERM="ansi";
        PATHSEP=";";
        ;;
    [Ll][Ii]][Nn][Uu][Xx])
        TERM="linux";
        PATHSEP=":";
        ;;
    [Aa][Ii][Xx]|[Ss][Uu][Nn][Oo][Ss]|[Ss][Oo]][Ll][Aa][Rr][Ii][Ss])
        TERM="ansi";
        PATHSEP=":";
        ;;
esac
