#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  path
#         USAGE:  . path
#   DESCRIPTION:  Sets environment path
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

## path
declare -x PATH="${PATH}:${HOME}/.bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/games";
declare -x MANPATH="/usr/man:/usr/local/man:/usr/share/man";

## libpath
declare -x LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/lib:/lib64:/usr/lib:/usr/lib64:/usr/local/lib:/usr/local/lib64";
declare -x LIBPATH="${LD_LIBRARY_PATH}";
declare -x LIB_PATH="${LD_LIBRARY_PATH}";
declare -x LD_RUN_PATH="${LD_LIBRARY_PATH}";

if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]]; then
    writeLogEntry "DEBUG" "${CNAME}" "P02-path" "${LINENO}" "PATH -> ${PATH}" 2>/dev/null;
    writeLogEntry "DEBUG" "${CNAME}" "P02-path" "${LINENO}" "MANPATH -> ${MANPATH}" 2>/dev/null;
    writeLogEntry "DEBUG" "${CNAME}" "P02-path" "${LINENO}" "LD_LIBRARY_PATH -> ${LD_LIBRARY_PATH}" 2>/dev/null;
    writeLogEntry "DEBUG" "${CNAME}" "P02-path" "${LINENO}" "LIBPATH -> ${LIBPATH}" 2>/dev/null;
    writeLogEntry "DEBUG" "${CNAME}" "P02-path" "${LINENO}" "LIB_PATH -> ${LIB_PATH}" 2>/dev/null;
    writeLogEntry "DEBUG" "${CNAME}" "P02-path" "${LINENO}" "LD_RUN_PATH -> ${LD_RUN_PATH}" 2>/dev/null;
fi

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
