#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  shopt
#         USAGE:  . shopt
#   DESCRIPTION:  Sets shell environment options
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

case "$(awk -F "/" '{print $NF}' <<< "${SHELL}")" in
    [Bb][Aa][Ss][Hh])
        shopt -s expand_aliases 2>/dev/null;
        shopt -s huponexit 2>/dev/null;
        shopt -s mailwarn 2>/dev/null;
        shopt -s histreedit 2>/dev/null;
        shopt -s histappend 2>/dev/null;
        shopt -s histverify 2>/dev/null;
        shopt -s hostcomplete 2>/dev/null;
        shopt -s cmdhist 2>/dev/null;
        shopt -s checkwinsize 2>/dev/null;
        shopt -s checkhash 2>/dev/null;
        shopt -s cdspell 2>/dev/null;
        shopt -s dirspell 2>/dev/null;
        shopt -s mailwarn 2>/dev/null;
        shopt -s checkjobs 2>/dev/null;
        ;;
esac

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
