#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  prompt
#         USAGE:  . prompt
#   DESCRIPTION:  Sets custom shell prompt
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

declare -x PROMPT_COMMAND=setPromptCommand;
