#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  history
#         USAGE:  . history
#   DESCRIPTION:  Configures shell command history handling
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

case "$(awk -F "/" '{print $NF}' <<< "${SHELL}")" in
    [Kk][Ss][Hh])
        declare -x HISTFILE="${HOME}/.ksh_history";
        declare -ix HISTSIZE=10000;
        declare -x EXTENDED_HISTORY="ON";
        ;;
    [Bb][Aa][Ss][Hh])
        declare -x HISTFILE="${HOME}/.bash_history";
        declare -ix HISTSIZE=10000;
        declare -ix HISTFILESIZE=10000;
        declare -x HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S ";
        declare -x HISTCONTROL="ignoredups:ignorespace";
        declare -x HISTIGNORE="ls:ll:lt:la:l:cd:pwd:exit:mc:su:df:clear:cls:bg:fg";
        ;;
esac

if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]]; then
    writeLogEntry "DEBUG" "${CNAME}" "P09-history" "${LINENO}" "HISTFILE -> ${HISTFILE}";
    writeLogEntry "DEBUG" "${CNAME}" "P09-history" "${LINENO}" "HISTSIZE -> ${HISTSIZE}";
    writeLogEntry "DEBUG" "${CNAME}" "P09-history" "${LINENO}" "EXTENDED_HISTORY -> ${EXTENDED_HISTORY}";
    writeLogEntry "DEBUG" "${CNAME}" "P09-history" "${LINENO}" "HISTFILESIZE -> ${HISTFILESIZE}";
    writeLogEntry "DEBUG" "${CNAME}" "P09-history" "${LINENO}" "HISTTIMEFORMAT -> ${HISTTIMEFORMAT}";
    writeLogEntry "DEBUG" "${CNAME}" "P09-history" "${LINENO}" "HISTCONTROL -> ${HISTCONTROL}";
    writeLogEntry "DEBUG" "${CNAME}" "P09-history" "${LINENO}" "HISTIGNORE -> ${HISTIGNORE}";
fi

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
