#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  mail
#         USAGE:  . mail
#   DESCRIPTION:  Configures mail handling
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

declare -x MAIL="/var/spool/mail/${LOGNAME:?}";
declare -ix MAILCHECK=10;

if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]]; then
    writeLogEntry "DEBUG" "${CNAME}" "P10-mail" "${LINENO}" "MAIL -> ${MAIL}" 2>/dev/null;
    writeLogEntry "DEBUG" "${CNAME}" "P10-mail" "${LINENO}" "MAILCHECK -> ${MAILCHECK}" 2>/dev/null;
fi

[[ ! -d "${HOME}/.mail" ]] && mkdir -pv "${HOME}/.mail";
#[ ! -z "$(/usr/bin/env mail -E 2>/dev/null)" ] && echo "$(/usr/bin/env mail -E)";

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
