#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  proxy
#         USAGE:  . proxy
#   DESCRIPTION:  Sets proxy rules
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

declare -x http_proxy="";
declare -x https_proxy="";
declare -x ftp_proxy="";

if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]]; then
    writeLogEntry "DEBUG" "${CNAME}" "P11-proxy" "${LINENO}" "http_proxy -> ${http_proxy}";
    writeLogEntry "DEBUG" "${CNAME}" "P11-proxy" "${LINENO}" "https_proxy -> ${https_proxy}";
    writeLogEntry "DEBUG" "${CNAME}" "P11-proxy" "${LINENO}" "ftp_proxy -> ${ftp_proxy}";
fi

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
