appservers:
  hosts:
    fedora-appserver.mgmt.caspersbox.com:
      was_servers:
        - AppSrv01
    fedora-portalserver.caspersbox.com:
      was_servers:
        - WebSphere_Portal
        - Search01

webservers:
  hosts:
    fedora-webserver.mgmt.caspersbox.com:
      ihs_servers:
        - admin
        - AppSrv
