#======  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
#=============================================================================
---
- name: Run postup healthcheck
  hosts: webservers
  roles:
    - postup
    - healthcheck
