# =====  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
# ============================================================================
---
- name: Run postup healthcheck

  pre_tasks:

  hosts: webservers
  roles:
    - postup
    - healthcheck

  post_tasks:
