#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  java
#         USAGE:  . java
#   DESCRIPTION:  Sets Java variables and path
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

case $(uname -s) in
    [Cc][Yy][Gg][Ww][Ii][Nn]*)
        if [[ -d "/cygdrive/c/PROGRA~1/Java/jdk-18.0.1.1" ]]; then declare -x JAVA_HOME="/cygdrive/c/PROGRA~1/Java/jdk-18.0.1.1"; fi
        ;;
    *)
        if [[ -d "/usr/java/latest" ]] || [[ -L "/usr/java/latest" ]]; then declare -x JAVA_HOME="/usr/java/latest"; fi
        if [[ -d "/usr/java/latest/jre" ]] || [[ -L "/usr/java/latest/jre" ]]; then declare -x JRE_HOME="/usr/java/latest/jre"; fi
        ;;
esac

if [[ -n "${JAVA_HOME}" ]]; then
    declare -x PATH="${PATH}:${JAVA_HOME}/bin";
    declare -x LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${JAVA_HOME}/bin:${JAVA_HOME}/lib";
    declare -x LIBPATH="${LD_LIBRARY_PATH}:${JAVA_HOME}/bin:${JAVA_HOME}/lib";
    declare -x LIB_PATH="${LD_LIBRARY_PATH}:${JAVA_HOME}/bin:${JAVA_HOME}/lib";
    declare -x CLASSPATH=".:${CLASSPATH}:${HOME}/etc:${HOME}/.lib";
    declare -x JAVA_EXT_DIRS="${JAVA_EXT_DIRS}:${JRE_HOME}/lib/ext:${WAS_EXT_DIRS}";
    declare -x JAVA_ENDORSED_DIRS="${JAVA_ENDORSED_DIRS}:${JRE_HOME}/lib/endorsed:${WAS_ENDORSED_DIRS}";
    declare -x JAVA_OPTS="-cp ${CLASSPATH} -verbose:gc -Xms256m -Xmx256m -XX:NewSize=96m -XX:MaxNewSize=96m -XX:+UseGCOverheadLimit -XX:+AggressiveOpts"
    declare -x JAVA_OPTS="${JAVA_OPTS} -XX:SurvivorRatio=16 -XX:+HeapDumpOnOutOfMemoryError -XX:ParallelGCThreads=4 -XX:+PrintGCDetails";
    declare -x JAVA_OPTS="${JAVA_OPTS} -XX:+PrintGCTimeStamps -XX:+AggressiveHeap -XX:+ScavengeBeforeFullGC -XX:-UseConcMarkSweepGC";
    declare -x JAVA_OPTS="${JAVA_OPTS} -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djavax.net.debug=all -Djava.ext.dirs=${JAVA_EXT_DIRS} -Djava.endorsed.dirs=${JAVA_ENDORSED_DIRS}";
fi

## path for ${JRE_HOME}
if [[ -n "${JRE_HOME}" ]]; then
    declare -x PATH="${PATH}:${JAVA_HOME}/bin";
    declare -x LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${JRE_HOME}/bin:${JRE_HOME}/lib";
    declare -x LIBPATH="${LD_LIBRARY_PATH}:${JRE_HOME}/bin:${JRE_HOME}/lib";
    declare -x LIB_PATH="${LD_LIBRARY_PATH}:${JRE_HOME}/bin:${JRE_HOME}/lib";
fi

if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]]; then
    writeLogEntry "DEBUG" "${CNAME}" "P01-java" "${LINENO}" "JAVA_HOME -> ${JAVA_HOME}";
    writeLogEntry "DEBUG" "${CNAME}" "P01-java" "${LINENO}" "JRE_HOME -> ${JRE_HOME}";
    writeLogEntry "DEBUG" "${CNAME}" "P01-java" "${LINENO}" "PATH -> ${PATH}";
    writeLogEntry "DEBUG" "${CNAME}" "P01-java" "${LINENO}" "LD_LIBRARY_PATH -> ${LD_LIBRARY_PATH}";
    writeLogEntry "DEBUG" "${CNAME}" "P01-java" "${LINENO}" "LIBPATH -> ${LIBPATH}";
    writeLogEntry "DEBUG" "${CNAME}" "P01-java" "${LINENO}" "LIB_PATH -> ${LIB_PATH}";
    writeLogEntry "DEBUG" "${CNAME}" "P01-java" "${LINENO}" "CLASSPATH -> ${CLASSPATH}";
    writeLogEntry "DEBUG" "${CNAME}" "P01-java" "${LINENO}" "JAVA_EXT_DIRS -> ${JAVA_EXT_DIRS}";
    writeLogEntry "DEBUG" "${CNAME}" "P01-java" "${LINENO}" "JAVA_ENDORSED_DIRS -> ${JAVA_ENDORSED_DIRS}";
    writeLogEntry "DEBUG" "${CNAME}" "P01-java" "${LINENO}" "JAVA_OPTS -> ${JAVA_OPTS}";
fi

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
