#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  P01-ihsgsk
#         USAGE:  . PA1-ihsgsk
#   DESCRIPTION:  Sets environment path
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

case "$(whoami)" in
    ihsadm)
        [[ ! -d "/opt/IBM/HTTPServer" ]] && return;

        declare -x PATH="${PATH}:/opt/IBM/HTTPServer/gsk8/bin";
        declare -x LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/IBM/HTTPServer/gsk8/lib64";
        ;;
    wasadm)
        [[ ! -d "/opt/IBM/WebSphere/Plugins" ]] && return;

        declare -x PATH="${PATH}:/opt/IBM/WebSphere/Plugins/gsk8/gsk8_64/bin";
        declare -x LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/IBM/WebSphere/Plugins/gsk8/gsk8_64/lib64";
        ;;
    *)
        return;
esac

if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]]; then
    writeLogEntry "DEBUG" "${CNAME}" "P01-gsk" "${LINENO}" "PATH -> ${PATH}";
    writeLogEntry "DEBUG" "${CNAME}" "P01-gsk" "${LINENO}" "LD_LIBRARY_PATH -> ${LD_LIBRARY_PATH}";
fi

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
