#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  ansible
#         USAGE:  . ansible
#   DESCRIPTION:  Loads keychain and adds available keys to it
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

[[ -d /opt/IBM/WebSphere/AppServer ]] || return;

declare -x OTEL_JAVAAGENT_ENABLED=false;

for WAS_PROFILE in $(ls -ltr /opt/IBM/WebSphere/profiles | grep ^d | awk '{print $NF}' | cut -d "/" -f 1); do
    source ${WAS_PROFILE}/bin/setupCmdLine.sh;
done
