#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  P01-websphere
#         USAGE:  . P01-websphere
#   DESCRIPTION:  Sets up the shell for WebSphere
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

declare -x OTEL_JAVAAGENT_ENABLED=false;

[[ -d "/opt/IBM/WebSphere/AppServer" ]] || return;

declare WAS_HOME="/opt/IBM/WebSphere/AppServer";
declare WAS_PROFILE_PATH="/opt/IBM/WebSphere/AppServer/profiles";
declare PATH="${PATH}:${WAS_HOME}/bin";

if [[ -d "${HOME}/lib/WebSphere/AppServer" ]]; then
    for file_entry in "${HOME}/lib/WebSphere/AppServer/*"; do
        [[ -z "${file_entry}" ]] && continue;

        if [[ -r "${file_entry}" ]] && [[ -s "${file_entry}" ]]; then source "${file_entry}"; fi

        [[ -n "${file_entry}" ]] && unset -v file_entry;
    done

    [[ -n "${file_entry}" ]] && unset -v file_entry;
fi

[[ -d "/opt/IBM/WebSphere/PortalServer" ]] || return;

declare WPS_HOME="/opt/IBM/WebSphere/PortalServer";
declare WPS_PROFILE_PATH="/opt/IBM/WebSphere/profiles";

if [[ -d "${HOME}/lib/WebSphere/PortalServer" ]]; then
    for file_entry in "${HOME}/lib/WebSphere/PortalServer/*"; do
        [[ -z "${file_entry}" ]] && continue;

        if [[ -r "${file_entry}" ]] && [[ -s "${file_entry}" ]]; then source "${file_entry}"; fi

        [[ -n "${file_entry}" ]] && unset -v file_entry;
    done

    [[ -n "${file_entry}" ]] && unset -v file_entry;
fi
