#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  A06-websphere
#         USAGE:  . A06-websphere
#   DESCRIPTION:  Aliases for WebSphere Server Management
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ ! -n "${USER_INSTALL_ROOT}" ]] && [[ -d "${USER_INSTALL_ROOT}" ]]; then
    alias stopManager='${USER_INSTALL_ROOT}/bin/stopManager.sh';
    alias startManager='${USER_INSTALL_ROOT}/bin/startManager.sh';

    alias stopNode='${USER_INSTALL_ROOT}/bin/stopNode.sh';
    alias startNode='${USER_INSTALL_ROOT}/bin/startNode.sh';

    alias stopServer='${USER_INSTALL_ROOT}/bin/stopServer.sh';
    alias startServer='${USER_INSTALL_ROOT}/bin/startServer.sh';

    alias PortalLogs='cd ${USER_INSTALL_ROOT}/logs/WebSphere_Portal';

    alias wsadmin='${USER_INSTALL_ROOT}/bin/wsadmin.sh -lang jython';
    alias runCCT='${USER_INSTALL_ROOT}/bin/wsadmin.sh -conntype NONE -f /nas/software/IBM/WAS/CCT/ConfigDump.py';
fi
