# =====  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
# ============================================================================
---
service_account: wasadm
install_path: /opt/IBM/WebSphere/AppServer
profiles_path: /opt/IBM/WebSphere/profiles
