#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  A02-git
#         USAGE:  . git
#   DESCRIPTION:  Useful git aliases
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

(( $(compgen -c | grep -Ew "^git" > /dev/null 2>&1; echo ${?}) == 0 )) || return;

## git
alias ga="git add";
alias gp="git push";
alias gl="git log";
alias gs="git status";
alias gd="git diff";
alias gdc="git diff --cached";
alias gm="git commit -m";
alias gma="git commit -am";
alias gms="git commit -Ssm";
alias rgc="git commit -m \"\$(curl -s https://whatthecommit.com/index.txt)"\";
alias gb="git branch";
alias gc="git checkout";
alias gr="git rm";
alias gra="git remote add";
alias grr="git remote rm";
alias gpu="git pull";
alias gcl="git clone";

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
