#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  java
#         USAGE:  . java
#   DESCRIPTION:  Useful java aliases
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

case $(uname -s) in
    [Cc][Yy][Gg][Ww][Ii][Nn]*)
        if [[ ! -d "/cygdrive/c/PROGRA~1/Java/jdk-18.0.1.1" ]]; then return; else typeset -x JAVA_HOME="/cygdrive/c/PROGRA~1/Java/jdk-18.0.1.1"; fi
        ;;
    *)
        if [[ ! -d /usr/java/latest ]] || [[ ! -L /usr/java/lates ]]; then return; else typeset -x JAVA_HOME="/usr/java/latest"; fi
        ;;
esac

## java

alias java="${JAVA_HOME}/bin/java ${JAVA_OPTS}";
alias keytool="${JAVA_HOME}/bin/keytool";
alias jad="~/.bin/jad -dead -ff -i -s java -t4";
alias threadAnalyzer="java -jar ${HOME}/.lib/jca457.jar";
alias heapAnalyzer="java -jar ${HOME}/.lib/ha456.jar";

if [[ -r "${HOME}/etc/SecurityService/config/PasswordRepository.config" ]]; then . "${HOME}/etc/SecurityService/config/PasswordRepository.config"; fi
alias javaPasswordRepository="java -cp \".:${UTILITY_CLASSPATH}:${PASSWORD_UTILITY_JAR}\" ${PASSWORD_UTILITY_CLASS}";

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
