#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  A03-sudo
#         USAGE:  . A03-sudo
#   DESCRIPTION:  Useful sudo aliases
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

## sudo aliases
alias ecuser="sudo su - ecuser";
alias sysadmin="sudo su - sysadmin";
alias ihsadm="sudo su - ihsadm";
alias appadm="sudo su - appadm";
alias webadm="sudo su - webadm";
alias wasadm="sudo su - wasadm";
alias dnsadm="sudo su - dnsadm";
alias db2adm="sudo su - db2adm";
alias ldapadm="sudo su - ldapadm";
alias zimbra="sudo su - zimbra";
alias root="sudo su -";
