#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  safety
#         USAGE:  . safety
#   DESCRIPTION:  Add safety measures to destructive commands
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

## safety
case "$(uname)" in
    [Aa][Ii][Xx])
        alias rm="rm -i";
        alias mv="mv -i";
        alias cp="cp -i";
        alias ln="ln -i";
        ;;
    *)
        alias rm="rm -i --preserve-root";
        alias chown="chown --preserve-root";
        alias chmod="chmod --preserve-root";
        alias chgrp="chgrp --preserve-root";
        alias mv="mv -i";
        alias cp="cp -i";
        alias ln="ln -i";
        ;;
esac

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
