#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  sudo
#         USAGE:  . sudo
#   DESCRIPTION:  Useful sudo aliases
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

## sudo aliases
alias ecuser="sudo su - ecuser";
alias sysadmin="sudo su - sysadmin";
alias ihsadm="sudo su - ihsadm";
alias appadm="sudo su - appadm";
alias webadm="sudo su - webadm";
alias wasadm="sudo su - wasadm";
alias dnsadm="sudo su - dnsadm";
alias db2adm="sudo su - db2adm";
alias ldapadm="sudo su - ldapadm";
alias zimbra="sudo su - zimbra";
alias root="sudo su -";

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
