#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  A06-websphere
#         USAGE:  . A06-websphere
#   DESCRIPTION:  Aliases for WebSphere Server Management
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

[[ ! -d /usr1/IBM/WebSphere ]] || return;

if [[ -d /usr1/IBM/WebSphere/profiles/wp_profile ]]; then
    alias startServer='/usr1/IBM/WebSphere/profiles/wp_profile/bin/startServer.sh';
    alias stopServer='/usr1/IBM/WebSphere/profiles/wp_profile/bin/stopServer.sh';

    alias startNode='/usr1/IBM/WebSphere/profiles/wp_profile/bin/startNode.sh';
    alias stopNode='/usr1/IBM/WebSphere/profiles/wp_profile/bin/stopNode.sh';
fi

if [[ -d /usr1/IBM/WebSphere/profiles/dmgr01 ]]; then
    alias startManager='/usr1/IBM/WebSphere/profiles/dmgr01/bin/startManager.sh';
    alias stopManager='/usr1/IBM/WebSphere/profiles/wp_profile/bin/stopManager.sh';
fi

if [[ -d /usr1/IBM/WebSphere/profiles/PPSearch01 ]]; then
    alias startServer='/usr1/IBM/WebSphere/profiles/PPSearch01/bin/startServer.sh';
    alias stopServer='/usr1/IBM/WebSphere/profiles/PPSearch01/bin/stopServer.sh';

    alias startNode='/usr1/IBM/WebSphere/profiles/PPSearch01/bin/startNode.sh';
    alias stopNode='/usr1/IBM/WebSphere/profiles/PPSearch01/bin/stopNode.sh';
fi

if [[ -d /usr1/IBM/WebSphere/profiles/PPServices01 ]]; then
    alias startServer='/usr1/IBM/WebSphere/profiles/PPServices01/bin/startServer.sh';
    alias stopServer='/usr1/IBM/WebSphere/profiles/PPServices01/bin/stopServer.sh';

    alias startNode='/usr1/IBM/WebSphere/profiles/PPServices01/bin/startNode.sh';
    alias stopNode='/usr1/IBM/WebSphere/profiles/PPServices01/bin/stopNode.sh';
fi

if [[ -d /usr1/IBM/WebSphere/profiles/PPServices02 ]]; then
    alias startServer='/usr1/IBM/WebSphere/profiles/PPServices02/bin/startServer.sh';
    alias stopServer='/usr1/IBM/WebSphere/profiles/PPServices02/bin/stopServer.sh';

    alias startNode='/usr1/IBM/WebSphere/profiles/PPServices02/bin/startNode.sh';
    alias stopNode='/usr1/IBM/WebSphere/profiles/PPServices02/bin/stopNode.sh';
fi
