#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  A17-zimbra
#         USAGE:  . A17-zimbra
#   DESCRIPTION:  Sets application-wide functions
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

if [[ ! -d /opt/zimbra ]] && [[ "$(whoami)" != "zimbra" ]]; then return; fi

alias zmcontrol="/opt/zimbra/bin/zmcontrol";
alias zmprov="/opt/zimbra/bin/zmprov";
alias zmysql="/opt/zimbra/bin/mysql -u zimbra -p";
alias jstack="/opt/zimbra/java/bin/jstack";
alias zmstats="/opt/zimbra/bin zmstat lmtp_threads http_threads db_conn_count db_pool_size gc_major_count | tail";
alias ldapsearch="/opt/zimbra/bin/ldapsearch -H \"/opt/zimbra/bin/zmlocalconfig -s -m nokey ldap_url | awk '{print $1}')\" -D \"$(/opt/zimbra/bin/zmlocalconfig -s -m nokey zimbra_ldap_userdn)\" -w \"$(/opt/zimbra/bin/zmlocalconfig -s -m nokey zimbra_ldap_password | awk '{print $1}')\" -LLL";

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
