#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  A07-ihs
#         USAGE:  . A07-ihs
#   DESCRIPTION:  Customizations
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

[[ -d /usr1/IBM/HTTPServer ]] || return;

alias startApache='/usr1/IBM/HTTPServer/bin/apachectl -k start';
alias stopApache='/usr1/IBM/HTTPServer/bin/apachectl -k stop';
