#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  A07-slapd
#         USAGE:  . A07-slapd
#   DESCRIPTION:  Sets IBM LDAP aliases
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

if [[ ! -d /opt/ibm/ldap ]] && [[ "$(whoami)" != "ldapadm" ]]; then return; fi

alias startldap="sudo -u root systemctl start ibm-directory-server";
alias stopldap="sudo -u root systemctl stop ibm-directory-server";
alias startadmin="sudo -u root systemctl start ibm-directory-admin";
alias stopadmin="sudo -u root systemctl stop ibm-directory-admin";

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
