#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  A09-named
#         USAGE:  . A09-named
#   DESCRIPTION:  Sets named functions and aliases
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

if [[ ! -d /var/named ]] || [[ "$(whoami)" != "dnsadm" ]]; then return; fi

alias freeze="sudo -u named /usr/sbin/rndc freeze";
alias thaw="sudo -u named /usr/sbin/rndc thaw";
alias notify="sudo -u named /usr/sbin/rndc notify";
alias reconfig="sudo -u named /usr/sbin/rndc reconfig";
alias reload="sudo -u named /usr/sbin/rndc reload";

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
