#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  custom
#         USAGE:  . custom
#   DESCRIPTION:  Customizations
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

## customs
alias lt="ls -ltrhpF --color=auto";
alias la="ls -ltrahpF --color=auto";
alias ll="ls -lhpF --color=auto";
alias ll.="ls -ltrdhpF .* --color=auto";
alias li="ls -iltrhpF --color=auto";
alias li.="ls -iltrahpF --color=auto";
alias ld="ls -ldhpF --color=auto";
alias sizeof="du -sk";
alias mktd="pushd $(mktemp)";
alias stamp="date \"+%Y%m%d %H:%M:%S\"";
alias da="date \"+%Y-%m-%d %A    %T %Z\"";
alias zero="cat /dev/null >|";
alias ssh="ssh -qt4AC";
alias removeKey="ssh-keygen -R";
alias win2unix="sed 's/$/\r/'";
alias fixtty="stty sane";
alias time="time --format=\"%C took %e seconds\"";
alias pdftotext="pdftotext -enc UTF-8 -layout";
alias ff="find . -type f";
alias fd="find . -type d";
alias clearScroll="printf \"\033c\"";
alias icanhazip="dig +short @resolver1.opendns.com myip.opendns.com";
alias fortune="fortune -a -e";
alias ipv4sort="sort -t . -k 1,1 -k 2,2 -k 3,3 -k 4,4";
alias minicom="sudo -u root minicom -s /dev/ttyS0";
alias tailf="tail -f";

## script tracing
alias enableDebug="declare -x ENABLE_DEBUG=\"${_TRUE}"\";
alias enableVerbose="declare -x ENABLE_VERBOSE=\"${_TRUE}"\";
alias enableTrace="declare -x ENABLE_TRACE=\"${_TRUE}"\";
alias enablePerf="declare -x ENABLE_PERFORMANCE=\"${_TRUE}"\";
alias disableDebug="declare -x ENABLE_DEBUG=\"${_FALSE}"\";
alias disableVerbose="declare -x ENABLE_VERBOSE=\"${_FALSE}"\";
alias disableTrace="declare -x ENABLE_TRACE=\"${_FALSE}"\";
alias disablePerf="declare -x ENABLE_PERFORMANCE=\"${_FALSE}"\";

## expect
alias scp.exp="${HOME}/lib/scp.exp";
alias ssh.exp="${HOME}/lib/ssh.exp";
alias ssh-copy-id.exp="${HOME}/lib/sshCopyIdentity.exp";
alias sudo.exp="${HOME}/lib/sudo.exp";
alias rsync.exp="${HOME}/lib/rsync.exp";
alias gpg.exp="${HOME}/lib/gpg.exp";
alias keychain.exp="${HOME}/lib/keychain.exp";
alias telnet.exp="${HOME}/lib/telnet.exp";
alias reload="source ${HOME}/.bashrc";
alias listFunctions="compgen -A function";

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
#!/usr/bin/env bash

#==============================================================================
#
#          FILE:  custom
#         USAGE:  . custom
#   DESCRIPTION:  Customizations
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set -x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set -v; fi

## customs
alias lt="ls -ltrhpF --color=auto";
alias la="ls -ltrahpF --color=auto";
alias ll="ls -lhpF --color=auto";
alias ll.="ls -ltrdhpF .* --color=auto";
alias li="ls -iltrhpF --color=auto";
alias li.="ls -iltrahpF --color=auto";
alias ld="ls -ldhpF --color=auto";
alias sizeof="du -sk";
alias mktd="pushd $(mktemp)";
alias stamp="date \"+%Y%m%d %H:%M:%S\"";
alias da="date \"+%Y-%m-%d %A    %T %Z\"";
alias zero="cat /dev/null >|";
alias ssh="ssh -qt4AC";
alias removeKey="ssh-keygen -R";
alias win2unix="sed 's/$/\r/'";
alias fixtty="stty sane";
alias time="time --format=\"%C took %e seconds\"";
alias pdftotext="pdftotext -enc UTF-8 -layout";
alias ff="find . -type f";
alias fd="find . -type d";
alias clearScroll="printf \"\033c\"";
alias icanhazip="dig +short @resolver1.opendns.com myip.opendns.com";
alias fortune="fortune -a -e";
alias ipv4sort="sort -t . -k 1,1 -k 2,2 -k 3,3 -k 4,4";
alias minicom="sudo -u root minicom -s /dev/ttyS0";
alias tailf="tail -f";

## script tracing
alias enableDebug="declare -x ENABLE_DEBUG=\"${_TRUE}"\";
alias enableVerbose="declare -x ENABLE_VERBOSE=\"${_TRUE}"\";
alias enableTrace="declare -x ENABLE_TRACE=\"${_TRUE}"\";
alias enablePerf="declare -x ENABLE_PERFORMANCE=\"${_TRUE}"\";
alias disableDebug="declare -x ENABLE_DEBUG=\"${_FALSE}"\";
alias disableVerbose="declare -x ENABLE_VERBOSE=\"${_FALSE}"\";
alias disableTrace="declare -x ENABLE_TRACE=\"${_FALSE}"\";
alias disablePerf="declare -x ENABLE_PERFORMANCE=\"${_FALSE}"\";

## expect
alias scp.exp="${HOME}/lib/scp.exp";
alias ssh.exp="${HOME}/lib/ssh.exp";
alias ssh-copy-id.exp="${HOME}/lib/sshCopyIdentity.exp";
alias sudo.exp="${HOME}/lib/sudo.exp";
alias rsync.exp="${HOME}/lib/rsync.exp";
alias gpg.exp="${HOME}/lib/gpg.exp";
alias keychain.exp="${HOME}/lib/keychain.exp";
alias telnet.exp="${HOME}/lib/telnet.exp";
alias reload="source ${HOME}/.bashrc";
alias listFunctions="compgen -A function";

if [[ -n "${ENABLE_VERBOSE}" ]] && [[ "${ENABLE_VERBOSE}" == "${_TRUE}" ]]; then set +x; fi
if [[ -n "${ENABLE_TRACE}" ]] && [[ "${ENABLE_TRACE}" == "${_TRUE}" ]]; then set +v; fi
