# =====  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
# ============================================================================
---
- name: Main entry point for postup
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop:
    - systemd.yml
    - check-processtable.yml
