name: ShellCheck
on: [push, pull_request]

jobs:
  scan:
    name: ShellCheck Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      matrix:
        match: [ bin/* functions.d/* ./AppServer/scripts/bin/* ./AppServer/scripts/lib/* ./IHS/scripts/bin/* ./IHS/scripts/lib/* ./PortalServer/scripts/bin/* ./PortalServer/scripts/bin/* **/*.sh ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: false
      - name: Shellcheck Scan
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: '-x -s bash'
        with:
          severity: 'error'
          check_together: 'yes'
          format: 'gcc'
        if: ${{ success() }}
      - name: Shellcheck SARIF Scan
        uses: reactive-firewall/shellcheck-scan@v1
        with:
          match: ${{ matrix.match }}
          severity: 'warning'
          shell-format: 'bash'
          publish-artifacts: true
          format: 'json'
        if: ${{ success() }}
