name: Python Linter
on: [push, pull_request]

jobs:
  lint:
    name: Run python linter on wsadmin code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        src: [ ./AppServer/wsadmin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true
      - name: Run linter
        uses: sunnysid3up/python-linter@master
        with:
          source: ./AppServer/wsadmin