fuckit - uses: astral-sh/ruff-action@v3
  with:
    src: "./src"


steps:
 - uses: actions/checkout@v4
 - name: Python Linter
   uses: sunnysid3up/python-linter@master
   with:
     source: "src"
     mypy-options: "--ignore-missing-imports --show-error-codes"
     pylint-options: "--rcfile=setup.cfg"
     isort-options: "-w 100"
     django: true